name: Unit Tests

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
        matrix:
            node-version: [16.x, 18.x, 14.x]

    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js $11 matrix.node-version}}
          uses: actions/setup-node@v1
          with:
            node-version: s{{ matrix.node-version}}
        - name: npm install
          run: npm ci
        - name: tests
          run: npm test

        